on:
  push:
    tags:
      - v**
  workflow_dispatch:


jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - name: install dependencies and freeze
        run: |
          pip install poetry pyinstaller
          poetry install --no-root
          poetry run pyinstaller src/main.py --add-data data:data --onefile
          mkdir release
          mv dist/* release/
      - uses: ihiroky/archive-action@v1
        with:
          root_dir: release/
          file_path: vs_mod_manger-$env:RUNNER_OS.zip
      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: vs_mod_manger-$env:RUNNER_OS.zip
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - run: mkdir releases
      - uses: actions/download-artifact@v4
        with:
          path: releases/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            releases/vs_mod_manger-Windows.zip
            releases/vs_mod_manger-Linux.zip
